###
GET http://localhost:8080/locations/api
Accept: application/json

###
GET http://localhost:8080/locations/api/3
Accept: application/json

###
GET http://localhost:8080/locations/api?name=BudaPest
Accept: application/json

###
GET http://localhost:8080/locations/api/lat?minLat=50&maxLat=85&minLon=0&maxLon=50
Accept: application/json


