###
GET http://localhost:8080/locations/api
Accept: application/json

###
GET http://localhost:8080/locations/api?name=Szeged
Accept: application/json

###
GET http://localhost:8080/locations/api/lat?lat=0&lon=0
Accept: application/json


